home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

mysite11/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as orderviews

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('references/', views.references, name='references'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('product/', include('product.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('user/', include('user.urls'), name='user'),
    path('order/', include('order.urls')),
    path('shopcart/', orderviews.shopcart, name='shopcart'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),

]

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from product.models import Product

class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()


    def __str__(self):
        return self.product.title

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)



class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False )
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','address','phone','city']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.utils.crypto import get_random_string

from home.models import Setting
from order.models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from product.models import Category, Product
from user.models import UserProfile


def index(request):
    return HttpResponse ("Order Page")

@login_required(login_url='/login') # Check login
def addtoshopcart(request,id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # Access User Session information
    checkproduct = ShopCart.objects.filter(product_id=id)
    if checkproduct:
        control = 1
    else:
        control = 0
    if request.method == 'POST':  # if there is a post
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control == 1:  # Update  shopcart
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()  # save data
            else:  # Inser to Shopcart
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
        messages.success(request, "Product added to Shopcart ")
        return HttpResponseRedirect(url)

    else:  # if there is no post
        if control == 1:  # Update  shopcart
            data = ShopCart.objects.get(product_id=id, user_id=current_user.id)
            data.quantity += 1
            data.save()  #
        else:  # Inser to Shopcart
            data = ShopCart()  # model ile bağlantı kur
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()  #
        messages.success(request, "Product added to Shopcart")
        return HttpResponseRedirect('/shopcart_product')

@login_required(login_url='/login') # Check login
def shopcart(request):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    current_user = request.user  # Access User Session information
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total=0
    for rs in shopcart:
        total += rs.product.price * rs.quantity
    #return HttpResponse(str(total))
    context={'shopcart': shopcart,
             'category':category,
             'setting': setting,
             'total': total,
             }
    return render(request,'shopcart_products.html',context)

@login_required(login_url='/login') # Check login
def deletefromcart(request,id):
    current_user = request.user  # Access User Session information
    ShopCart.objects.filter(id=id).delete()
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
    messages.success(request, "Your item deleted form Shopcart.")
    return HttpResponseRedirect("/shopcart")


def orderproduct(request):
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity

    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        #return HttpResponse(request.POST.items())
        if form.is_valid():
            data = Order()
            data.first_name = form.cleaned_data['first_name'] #get product quantity from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode= get_random_string(5).upper() # random cod
            data.code =  ordercode
            data.save() #

            shopcart = ShopCart.objects.filter(user_id=current_user.id)
            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id     = data.id # Order Id
                detail.product_id   = rs.product_id
                detail.user_id      = current_user.id
                detail.quantity     = rs.quantity

                product = Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity
                product.save()

                detail.price =rs.product.price
                detail.amount = rs.amount
                detail.save()

            ShopCart.objects.filter(user_id=current_user.id).delete() # Clear & Delete shopcart
            request.session['cart_items']=0
            messages.success(request, "Your Order has been completed. Thank you ")
            return render(request, 'order_completed.html',{'ordercode':ordercode,'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form= OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'shopcart': shopcart,
               'category': category,
               'total': total,
               'form': form,
               'profile': profile,
               'setting': setting,
               }
    return render(request, 'order_form.html', context)

order/templates/order_completed.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %} Order Completed | {{ setting.title }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}


{% block content %}
<div id="mainBody">
	<div class="container">
	<div class="row">
<!-- Sidebar ================================================== -->
<div id="sidebar" class="span3">
		<div class="well well-small"><a id="myCart" href="/shopcart"><img src="{% static 'themes/images/ico-cart.png' %}" alt="cart">{{ request.session.cart_items }} Items in your cart  </a></div>
		<ul id="sideManu" class="nav nav-tabs nav-stacked">
			{% load mptt_tags %}
            {% recursetree category %}
			<li><a href="/category/{{ node.id }}/{{ node.slug }}">{{ node.title}}</a></li>
            {% endrecursetree %}
		</ul>
		<br/>

	</div>
<!-- Sidebar end=============================================== -->

	<div class="span9">
    <ul class="breadcrumb">
		<li><a href="/">Home</a> <span class="divider">/</span></li>
		<li class="active"> ORDER COMPLETED</li>
    </ul>
	<h3>  ORDER COMPLETED <a href="/" class="btn btn-large pull-right"><i class="icon-arrow-left"></i> Continue Shopping </a></h3>
	<hr class="soft"/>


	<hr>
                        <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2>
                        <hr>
                        <h3>Your order is completed</h3>
                        <h3>Order Code : {{ ordercode }}</h3>
                        <h3>Thank You</h3>
                        <hr>



	<a href="/" class="btn btn-large"><i class="icon-arrow-left"></i> Continue Shopping </a>

</div>
</div></div>
</div>
<!-- MainBody End ============================= -->
 {% endblock %}

order/templates/order_form.html
{% extends 'homebase.html' %}

{% block title %} Order Details | {{ setting.title }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% load static %}

{% block content %}
 <!-- Checkout Start -->
       <div id="mainBody">
	<div class="container">
	<div class="row">
<!-- Sidebar ================================================== -->
<div id="sidebar" class="span3">
		<div class="well well-small"><a id="myCart" href="/shopcart"><img src="{% static 'themes/images/ico-cart.png' %}" alt="cart">{{ request.session.cart_items }} Items in your cart  </a></div>
		<ul id="sideManu" class="nav nav-tabs nav-stacked">
			{% load mptt_tags %}
            {% recursetree category %}
			<li><a href="/category/{{ node.id }}/{{ node.slug }}">{{ node.title}}</a></li>
            {% endrecursetree %}
		</ul>
		<br/>

	</div>
<!-- Sidebar end=============================================== -->

	<div class="span9">
    <ul class="breadcrumb">
		<li><a href="/">Home</a> <span class="divider">/</span></li>
		<li class="active"> ORDER FORM</li>
    </ul>
                  <form action="" method="post">
                    {% csrf_token %}
                    <div class="col-lg-8" style="padding-left: 300px;">
                        <form class="checkout-inner">
                            <div class="billing-address">
                                <h2>Address</h2>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>First Name</label>
                                        <input class="form-control" name="first_name"  value="{{ user.first_name }}" type="text" placeholder="First Name">
                                    </div>
                                    <div class="col-md-6">
                                        <label>Last Name"</label>
                                        <input class="form-control" name="last_name"  value="{{ user.last_name }}" type="text" placeholder="Last Name">
                                    </div>
                                    <div class="col-md-6">
                                        <label>Mobile No</label>
                                        <input class="form-control" name="phone" value="{{ profile.phone }}" type="number" placeholder="Mobile No">
                                    </div>
                                    <div class="col-md-12">
                                        <label>Address</label>
                                        <input class="form-control" name="address" value="{{ profile.address }}" type="text" placeholder="Address">
                                    </div>
                                    <div class="col-md-6">
                                        <label>City</label>
                                        <select name="city" class="input" id="id_city">
                                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                    <option value="İstanbul">Istanbul</option>
                                    <option value="Ankara">Ankara</option>
                                    <option value="İzmir">Izmir</option>
                                    <option value="Bursa">Bursa</option>
                                    <option value="Konya">Konya</option>
                                    <option value="Yozgat">Yozgat</option>
                                </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Country</label>
                                        <input class="form-control" name="country" type="text" value="{{ profile.country }}" placeholder="City">
                                    </div>

                                </div>
                            </div>
                            <div class="col-md-6">
                        <div class="shiping-methods">
                            <div class="section-title">
                                <h4 class="title">Payment Information</h4>
                            </div>
                            <p><label for="id_first_name">Total: {{ total }} TL </label>
                                <input type="text" name="total" class="input" readonly value="{{ total }}TL"></p>
                            <p><label for="id_first_name">Credit Card Holder</label>
                                <input type="text" name="holder" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Card Number</label>
                                <input type="text" name="number" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Exp Date/Year</label>
                                <input type="text" name="ecpdate" class="input"  placeholder="mm/yy"></p>
                            <p><label for="id_first_name">Security Number</label>
                                <input type="text" name="secnumber" class="input"  value=""></p>
                        </div>
                        </div>


                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="checkout-inner">
                            <div class="checkout-summary">

                                <h2>Grand Total<span>{{total}}TL</span></h2>
                            </div>

                            <div class="checkout-payment">

                                <div class="checkout-btn">
                                    <button>Place Order</button>
                                </div>
                            </div>
                        </div>
                    </div>
                  </form>
                </div>
            </div>
        </div>
        <!-- Checkout End -->

    <!-- Cart Start -->
        <div class="cart-page">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Title</th>
				  <th>Price</th>
                  <th>Quantity</th>
                  <th>Total</th>
                    <th>Delete</th>
				</tr>
              </thead>
              <tbody>
              {% for rs in shopcart %}
                <tr>
                  <td> <img width="60" src="{{ rs.product.image.url }}" alt=""/></td>
                  <td>{{ rs.product.title }}</td>
                  <td>{{ rs.product.price }} TL</td>
                  <td>{{ rs.quantity }}</td>
                  <td>{{ rs.amount }}</td>
                <td><a href="/order/deletefromcart/{{ rs.id }}">DELETE</a></td>
                </tr>
				{% endfor %}

                <tr>
                  <td colspan="6" style="text-align:right">Total Price:	</td>
                  <td> {{ total }}TL</td>
                </tr>

				 <tr>
                  <td colspan="6" style="text-align:right"><strong>TOTAL  {{ total }}TL</strong></td>
                  <td class="label label-important" style="display:block"> <strong>  {{ total }}TL </strong></td>

                </tr>
				</tbody>
            </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Cart End -->

 {% endblock %}

order/templates/shopcart_products.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %} Shopcart Products | {{ setting.title }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}


{% block content %}
<div id="mainBody">
	<div class="container">
	<div class="row">
<!-- Sidebar ================================================== -->
<div id="sidebar" class="span3">
		<div class="well well-small"><a id="myCart" href="/shopcart"><img src="{% static 'themes/images/ico-cart.png' %}" alt="cart">{{ request.session.cart_items }} Items in your cart  </a></div>
		<ul id="sideManu" class="nav nav-tabs nav-stacked">
			{% load mptt_tags %}
            {% recursetree category %}
			<li><a href="/category/{{ node.id }}/{{ node.slug }}">{{ node.title}}</a></li>
            {% endrecursetree %}
		</ul>
		<br/>

	</div>
<!-- Sidebar end=============================================== -->

	<div class="span9">
    <ul class="breadcrumb">
		<li><a href="/">Home</a> <span class="divider">/</span></li>
		<li class="active"> SHOPPING CART [ {{ request.session.cart_items }} ]</li>
    </ul>
	<h3>  SHOPPING CART [ <small> {{ request.session.cart_items }} </small>]<a href="/" class="btn btn-large pull-right"><i class="icon-arrow-left"></i> Continue Shopping </a></h3>
	<hr class="soft"/>


	<table class="table table-bordered">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Title</th>
				  <th>Price</th>
                  <th>Quantity</th>
                  <th>Total</th>
                    <th>Delete</th>
				</tr>
              </thead>
              <tbody>
              {% for rs in shopcart %}
                <tr>
                  <td> <img width="60" src="{{ rs.product.image.url }}" alt=""/></td>
                  <td>{{ rs.product.title }}</td>
                  <td>{{ rs.product.price }} TL</td>
                  <td>{{ rs.quantity }}</td>
                  <td>{{ rs.amount }}</td>
                    <td><a href="/order/deletefromcart/{{ rs.id }}"><b>DELETE</b></a></td>
                </tr>
				{% endfor %}

                <tr>
                  <td colspan="6" style="text-align:right">Total Price:	</td>
                  <td> {{ total }}TL</td>
                </tr>

				 <tr>
                  <td colspan="6" style="text-align:right"><strong>TOTAL  {{ total }}TL</strong></td>
                  <td class="label label-important" style="display:block"> <strong>  {{ total }}TL </strong></td>
                </tr>
				</tbody>
            </table>



	<a href="/" class="btn btn-large"><i class="icon-arrow-left"></i> Continue Shopping </a>
	<a href="{% url 'orderproduct' %}" class="btn btn-large pull-right">Next <i class="icon-arrow-right"></i></a>

</div>
</div></div>
</div>
<!-- MainBody End ============================= -->
 {% endblock %}